name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-reading
        run: echo "helo world"
      - name: Print goodbye
        run: echo "done - bye!"
